# Generated by Django 4.1.4 on 2022-12-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_options_alter_post_catecory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catecory',
            new_name='category',
        ),
    ]
